language: node_js
node_js:
    - 0.12
env:
    - JASMINE_CONFIG_PATH=tests/support/jasmine.json
before_script:
    - "npm i -g jasmine-node"
    - "nohup node examples/citizen.js &"
    - "sleep 3"
    - "nohup node examples/citizenWithInvalidReturn.js &"
    - "sleep 3"
script:
    - "npm test"
    - "npm run-script coverage"
after_success:
    - "npm run-script coveralls"
