language: node_js
node_js:
    - 0.12
env:
    - JASMINE_CONFIG_PATH=tests/support/jasmine.json
    - COVERAGE=true
before_script:
    - "npm i -g jasmine-node"
script:
    - "npm test"
    - "npm run-script coverage"
after_success:
    - "npm run-script coveralls"
